include:
  - project: "fenrisdigital/devops/gitlab-ci-templates"
    file: "python/.python-project-gitlab-ci.yml"

variables:
  PROJECT_NAME: "demo_app.py"
  RUN_MYPY: "false"

mypy:
  stage: quality
  rules:
    - if: $RUN_MYPY == "true"
